export enum PageRouterEnum {
    Login= "/login",
    ForgotPassword= "/forgotPassword",
    Home= "/",
    Employees= "/employees",
    Charges= "/charges",
    Customers= "/customers",
    PotentialCustomers= "/potentialCustomers",
    ManagementProposals= "/managementProposals",
    RevisionProposals= "/revisionProposals",
    ContractManagement= "/contractManagement",
    Profiles= "/profiles",
    WasteManagement= "/wasteManagement",
    ContractClauses= "/contractClauses",
}